# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: "Main"
on: [ "push", "pull_request" ]

jobs:
  gradle:

    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        # TODO: arch: [ "x64", "arm64" ]

    runs-on: "${{ matrix.os }}"

    steps:

    - uses: "actions/checkout@v3"

    - uses: "actions/setup-java@v3"
      with:
        distribution: "temurin"
        java-version: "11"

    - uses: "gradle/gradle-build-action@v2"

    - run: "./gradlew jvmTest"

    # Build for all platforms
    - run: "./gradlew build -x check -x lintVitalRelease"

    # Publish artifacts to GitHub
    - name: "Publish artifacts"
      uses: "actions/upload-artifact@v3"
      with:
        name: "artifacts"
        path: |
          build/distributions/
          build/outputs/apk/release/
          build/libs/
